###############################################################################
# Author: <Your Name>
# Name: TechNight-WebAPI-CICD (Workflow)
#
# Workflow used to package, deploy, and configure the TechNight-WebAPI
###############################################################################

name: TechNight-WebAPI-CICD

env:
  DOTNET_VERSION: '6.0'
  WEBAPP_BASE_PATH: 'My-WebAPI'

on:
  push:
    branches: [ "main" ]
    paths:
      #TODO: Add path to WebAPI project
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual build from GitHub UI'

# Write permissions are the minimal required by the Publish Test Results action
# https://github.com/EnricoMi/publish-unit-test-result-action#permissions
permissions:
  checks: write
  pull-requests: write

jobs:

########################
# BUILD STAGE
########################
  build:
    runs-on: ubuntu-latest

    outputs:
      AZURE_WEBAPP_NAME: ${{ steps.setEnvVariables.outputs.AZURE_WEBAPP_NAME }}
      RESOURCE_GROUP: ${{ steps.setEnvVariables.outputs.RESOURCE_GROUP }} 

    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # As of June 2023, GH offers no built-in way to pass environment variables to a
      # reusable workflow. This is a workaround as suggested in this thread: 
      # https://github.com/orgs/community/discussions/26671
      - name: Set variables to be passed to the reusable workflow
        id: setEnvVariables
        run: |
          echo "AZURE_WEBAPP_NAME=<YOUR-WEBAPP-NAME>" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_GROUP=<YOUR-RG-NAME>"        >> "$GITHUB_OUTPUT"

      # Add Action to Setup .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: #TODO: Add .NET Core version

      # TODO: Add Action to Build Web App
      # TODO: Add Action to Run Unit Tests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ env.WEBAPP_BASE_PATH }}/**/*.xml
            ${{ env.WEBAPP_BASE_PATH }}/**/*.trx
            ${{ env.WEBAPP_BASE_PATH }}/**/*.json

      # TODO: Add Action to Publish Web App 
      # TODO: Add Action to Upload Web App Artifacts for Deployment
      # TODO: Add Action to Upload Bicep Template for Deployment

########################
# DEVELOPMENT STAGE 
########################
  dev:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment: <ENVIRONMENT-NAME>

    # TODO: declare environment variables for the dev environment prefix

    steps:

      # Download the artifacts from the build job (actions/download-artifact@v3)
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: <YOUR-ARTIFACT-NAME>

      #TODO: Add action to login to Azure (azure/login@v1)
      #TODO: Add action to deploy the Web App Bicep Template (azure/arm-deploy@v1)
      #TODO: Add action to deploy the Web App Artifacts (azure/webapps-deploy@v2)
      #TODO: Add action to configure the Web App Settings (azure/appservice-settings@v1)
      #TODO: Add action to log out of Azure 

##############################
# PRODUCTION STAGE (FOR LATER)
##############################
#  prd:
      # without the below if statement the job will be displayed as "failed" if a change 
      # isn't coming from the develop or main branch
#      if: github.ref == 'refs/heads/main' 
#      needs: [build, dev]
#      uses: ./.github/workflows/webapp-deploy-template.yml
#      permissions:
#          contents: none
#      with:
#        ENVIRONMENT_PREFIX: PRD
#        ENVIRONMENT: PRODUCTION
#        AZURE_WEBAPP_NAME: ${{ needs.build.outputs.AZURE_WEBAPP_NAME }}
#        RESOURCE_GROUP: ${{ needs.build.outputs.RESOURCE_GROUP }}
#        STARTUP_COMMAND: "dotnet WebAPI.dll"
#        AZURE_WEBAPP_SKU: B1
#      secrets: inherit